2025-07-14 12:37:54 | INFO     | natal_mobile_auto.conftest:pytest_runtest_setup:99 - Starting test: test_NAF_2_2_0_login_flow
2025-07-14 12:37:54 | INFO     | natal_mobile_auto.conftest:setup_and_teardown_test:60 - Setting up test function
2025-07-14 12:37:54 | INFO     | natal_mobile_auto.tests.test_2_Authentication:setup_and_teardown:22 - Setting up test environment with app restart
2025-07-14 12:37:54 | INFO     | core.driver_manager:_create_driver:43 - {'platformName': 'Android', 'platformVersion': '14.0', 'deviceName': '127.0.0.1:6555', 'appPackage': 'com.natalllc.dev', 'appActivity': 'com.natalllc.dev.MainActivity', 'automationName': 'UiAutomator2', 'noReset': True, 'newCommandTimeout': 300, 'waitForIdleTimeout': 3000, 'uiautomator2ServerInstallTimeout': 60000, 'uiautomator2ServerLaunchTimeout': 60000, 'androidInstallTimeout': 90000, 'adbExecTimeout': 20000, 'autoGrantPermissions': True, 'skipServerInstallation': False, 'ignoreHiddenApiPolicyError': True}
2025-07-14 12:37:54 | INFO     | core.driver_manager:_create_driver:59 - Connecting to Appium server: http://127.0.0.1:4723
2025-07-14 12:37:54 | ERROR    | core.driver_manager:_create_driver:69 - Failed to create WebDriver: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a383790>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-07-14 12:37:54 | INFO     | natal_mobile_auto.conftest:pytest_runtest_teardown:104 - Completed test: test_NAF_2_2_0_login_flow
2025-07-14 12:37:54 | INFO     | natal_mobile_auto.conftest:setup_and_teardown_test:64 - Tearing down test function
2025-07-14 12:37:55 | INFO     | natal_mobile_auto.conftest:pytest_runtest_setup:99 - Starting test: test_NAF_2_2_0_login_flow
2025-07-14 12:37:55 | INFO     | natal_mobile_auto.conftest:setup_and_teardown_test:60 - Setting up test function
2025-07-14 12:37:55 | INFO     | natal_mobile_auto.tests.test_2_Authentication:setup_and_teardown:22 - Setting up test environment with app restart
2025-07-14 12:37:55 | INFO     | core.driver_manager:_create_driver:43 - {'platformName': 'Android', 'platformVersion': '14.0', 'deviceName': '127.0.0.1:6555', 'appPackage': 'com.natalllc.dev', 'appActivity': 'com.natalllc.dev.MainActivity', 'automationName': 'UiAutomator2', 'noReset': True, 'newCommandTimeout': 300, 'waitForIdleTimeout': 3000, 'uiautomator2ServerInstallTimeout': 60000, 'uiautomator2ServerLaunchTimeout': 60000, 'androidInstallTimeout': 90000, 'adbExecTimeout': 20000, 'autoGrantPermissions': True, 'skipServerInstallation': False, 'ignoreHiddenApiPolicyError': True}
2025-07-14 12:37:55 | INFO     | core.driver_manager:_create_driver:59 - Connecting to Appium server: http://127.0.0.1:4723
2025-07-14 12:37:55 | ERROR    | core.driver_manager:_create_driver:69 - Failed to create WebDriver: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3c3f00>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-07-14 12:37:56 | INFO     | natal_mobile_auto.conftest:pytest_runtest_teardown:104 - Completed test: test_NAF_2_2_0_login_flow
2025-07-14 12:37:56 | INFO     | natal_mobile_auto.conftest:setup_and_teardown_test:64 - Tearing down test function
2025-07-14 12:37:57 | INFO     | natal_mobile_auto.conftest:pytest_runtest_setup:99 - Starting test: test_NAF_2_2_0_login_flow
2025-07-14 12:37:57 | INFO     | natal_mobile_auto.conftest:setup_and_teardown_test:60 - Setting up test function
2025-07-14 12:37:57 | INFO     | natal_mobile_auto.tests.test_2_Authentication:setup_and_teardown:22 - Setting up test environment with app restart
2025-07-14 12:37:57 | INFO     | core.driver_manager:_create_driver:43 - {'platformName': 'Android', 'platformVersion': '14.0', 'deviceName': '127.0.0.1:6555', 'appPackage': 'com.natalllc.dev', 'appActivity': 'com.natalllc.dev.MainActivity', 'automationName': 'UiAutomator2', 'noReset': True, 'newCommandTimeout': 300, 'waitForIdleTimeout': 3000, 'uiautomator2ServerInstallTimeout': 60000, 'uiautomator2ServerLaunchTimeout': 60000, 'androidInstallTimeout': 90000, 'adbExecTimeout': 20000, 'autoGrantPermissions': True, 'skipServerInstallation': False, 'ignoreHiddenApiPolicyError': True}
2025-07-14 12:37:57 | INFO     | core.driver_manager:_create_driver:59 - Connecting to Appium server: http://127.0.0.1:4723
2025-07-14 12:37:57 | ERROR    | core.driver_manager:_create_driver:69 - Failed to create WebDriver: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a371d00>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-07-14 12:37:57 | INFO     | natal_mobile_auto.conftest:pytest_runtest_teardown:104 - Completed test: test_NAF_2_2_0_login_flow
2025-07-14 12:37:57 | INFO     | natal_mobile_auto.conftest:setup_and_teardown_test:64 - Tearing down test function
