{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103dfdcd0>: Failed to establish a new connection: [Errno 61] Connection refused'))","children":[{"name":"test_NAF_2_2_0_login_with_wrong_email","uid":"1ff1e504c5792935","parentUid":"d734ae34139da633ebc7564ae1ad6ac6","status":"broken","time":{"start":1753405217710,"stop":1753405217710,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["authentication"]}],"uid":"d734ae34139da633ebc7564ae1ad6ac6"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1069f2050>: Failed to establish a new connection: [Errno 61] Connection refused'))","children":[{"name":"test_NAF_3_2_0_update_bio","uid":"16a99283a59335cd","parentUid":"9475575106564cfe764508580cd929cd","status":"broken","time":{"start":1753405221431,"stop":1753405221431,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["personal","login"]}],"uid":"9475575106564cfe764508580cd929cd"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107be50d0>: Failed to establish a new connection: [Errno 61] Connection refused'))","children":[{"name":"test_NAF_4_2_0_valid_program_selection_and_start","uid":"1dd8d00dc73f64be","parentUid":"637f472bb493d93d8c0a3c325d64b2e7","status":"broken","time":{"start":1753405226384,"stop":1753405226384,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["program"]}],"uid":"637f472bb493d93d8c0a3c325d64b2e7"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105306490>: Failed to establish a new connection: [Errno 61] Connection refused'))","children":[{"name":"test_NAF_14_1_0_verify_community_feed_navigation","uid":"92a92e8f8185ca22","parentUid":"0bfca71d45bbb7663f0ee8322ecd6352","status":"broken","time":{"start":1753405230028,"stop":1753405230028,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["community"]}],"uid":"0bfca71d45bbb7663f0ee8322ecd6352"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103840a10>: Failed to establish a new connection: [Errno 61] Connection refused'))","children":[{"name":"test_logout_and_relogin","uid":"9dbd9aa875e5d372","parentUid":"204e7658ced41e556f565c9d7d0e0aca","status":"broken","time":{"start":1753405233738,"stop":1753405233738,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["logout"]}],"uid":"204e7658ced41e556f565c9d7d0e0aca"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}